# Generated by Django 4.2.16 on 2024-11-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_favorite_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='keyword',
            field=models.CharField(max_length=50, verbose_name='키워드'),
        ),
    ]
