# Generated by Django 4.2.16 on 2024-11-25 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='num_of_clicks',
        ),
    ]
