# Generated by Django 4.2.16 on 2024-11-22 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newskeywords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsKeywords',
            new_name='Keywords',
        ),
    ]
