# Generated by Django 4.2.16 on 2024-11-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_useraction_num_of_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.CharField(max_length=100),
        ),
    ]
