# Generated by Django 4.2.16 on 2024-11-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_newskeywords_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='intensity',
            field=models.FloatField(null=True),
        ),
    ]
