# Generated by Django 4.2.16 on 2024-11-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_keywords_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='keyword',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topkeywords',
            name='keyword',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='keyword',
            field=models.TextField(),
        ),
    ]
